course_physics = {
    "Aide à la réussite (partie A)" : ("Aide à la réussite","GREEN"),
    "Aide à la réussite (partie B)" : ("Aide à la réussite","GREEN"),
    "Alg. lin. et géom. I. B" : ("Algèbre linéaire et géométrie","GREEN"),
    "Alg. lin.et géom. I. A." : ("Algèbre linéaire et géométrie","GREEN"),
    "Anal. math. I." : ("Analyse mathématique I","GREEN"),
    "Chim. gén. A" : ("Chimie générale","YELLOW"),
    "Chim. gén. A ex. & TP" : ("Chimie générale A","YELLOW"),
    "Chim. gén. A.Ex. & TP" : ("Chimie générale A","YELLOW"),
    "Chimie générale (partie B)" : ("Chimie générale B","CYAN"),
    "Elec et magnétisme - Théorie" : ("Electricité et magnétisme","CYAN"),
    "Electro et magné - travaux dir" : ("Aide à la réussite","CYAN"),
    "Eval. continue math. élém." : ("Evaluation continue math élém.","GREEN"),
    "Evénement - DCOM" : ("Evenement - DCOM","GREY"),
    "Ex. approf. méthodo." : ("Exercice approfondi et méthodologie","GREEN"),
    "Géométrie dans plan & espace" : ("Math elem : Géométrie dans plan & espace","GREEN"),
    "Inégalités" : ("Math elem : Inégalités","GREEN"),
    "Logique" : ("Math elem : Logique","GREEN"),
    "Math. II" : ("Mathématiques II","GREEN"),
    "Mathématiques I" : ("Mathématiques I","GREEN"),
    "Matière à préciser" : ("Matière à préciser","GREEN"),
    "Mécanique - Théorie" : ("Mécanique","CYAN"),
    "Mécanique - travaux dirigés" : ("Mécanique","CYAN"),
    "Nombres complexes" : ("Nombres complexes","GREEN"),
    "ondes opt phys méca fluides t." : ("ondes opt phys méca fluides t.","CYAN"),
    "Opt géo et thermo - Theorie" : ("Opt géo et thermo","CYAN"),
    "Phys. gen. I cplts TD & TP" : ("Phys. gen. I cplts TD & TP","CYAN"),
    "Phys. gén. II. cplts TD et TP" : ("Phys. gén. II. cplts TD et TP","CYAN"),
    "Univers struct. const." : ("Univers struct. const.","CYAN"),


    "calcul tens et rel. rest." : ("Calcul tensiriel et relativité restreinte","CYAN"),
    "Compléments de mathématiques" : ("Compléments de mathématiques","GREEN"),
    "Electromagnétisme I" : ("Electromagnétisme I","CYAN"),
    "English for Science, part 1" : ("English for Science","GREY"),
    "English for Science, part 2" : ("English for Science","GREY"),
    "Exer. thermo" : ("Exercice thermo","CYAN"),
    "Mathématiques III" : ("Mathématiques III","GREEN"),
    "Méca classique I" : ("Mécanique classique I","CYAN"),
    "Phys.gén. III (B)" : ("Physique générale III","CYAN"),
    "Physique générale III (A)" : ("Physique générale III","CYAN"),
    "Physique nucléaire I Theorie" : ("Physique nucléaire I","CYAN"),
    "Physique nucléaire I TP" : ("Physique nucléaire I","CYAN"),
    "Probabilités" : ("Probabilités","CYAN"),
    "Programmation et algorithmiq I" : ("Programmation et algorithmique I","CYAN"),
    "Thermodyn I" : ("Thermodyn I","CYAN"),
}