course_dict = [("BAB1 - Architecture", "Architecture"),
("BAB1 - Droit", "Droit"),
("BAB1 - Ing. de gestion", "Ingénieur de gestion"),
("BAB1 - Ir. civil", "Polytech"),
("BAB1 - Ir. civil (Ch)", "Polytech"),
("BAB1 - Ir. civil architecte", "Polytech"),
("BAB1 - Médecine", "Médecine"),
("BAB1 - Sc. biologiques", "Sciences biologiques"),
("BAB1 - Sc. biologiques (Ch)", "Sciences biologiques"),
("BAB1 - Sc. biomédicales", "Sciences biomédicales"),
("BAB1 - Sc. biomédicales (remise à niveau)", "Sciences biomédicales"),
("BAB1 - Sc. chimiques", "Sciences chimiques"),
("BAB1 - Sc. de gestion", "Sciences de gestion"),
("BAB1 - Sc. de gestion (Ch)", "Sciences de gestion"),
("BAB1 - Sc. éco. et de gestion", "Sciences économiques et de gestion"),
("BAB1 - Sc. humaines et sociales", "SHS"),
("BAB1 - Sc. informatiques", "Sciences informatiques"),
("BAB1 - Sc. mathématiques", "Sciences mathématiques"),
("BAB1 - Sc. pharmaceutiques", "Sciences phamaceutiques"),
("BAB1 - Sc. physiques", "Sciences physiques"),
("BAB1 - Sc. psycho. et de l'éduc., or. générale", "Psychologie"),
("BAB1 - Sc. psycho. et de l'éduc., or. générale (Ch)", "Psychologie"),
("BAB1 - Sc. psycho. et de l'éduc., or. logopédie", "Psychologie"),
("BAB1 - Traduction et interprétation", "Traduction et interprétation"),
("BAB1 - Sc. humaines et sociales (Ch)", "SHS"),
("BAB2 - Architecture", "Architecture"),
("BAB2 - Droit", "Droit"),
("BAB2 - Ing. de gestion", "Ingénieur de gestion"),
("BAB2 - Ir. civil", "Polytech"),
("BAB2 - Ir. civil (Ch)", "Polytech"),
("BAB2 - Ir. civil architecte", "Polytech"),
("BAB2 - Médecine", "Médecine"),
("BAB2 - Sc. biologiques", "Sciences biologiques"),
("BAB2 - Sc. biologiques (Ch)", "Sciences biologiques"),
("BAB2 - Sc. biomédicales", "Sciences biomédicales"),
("BAB2 - Sc. chimiques", "Sciences chimiques"),
("BAB2 - Sc. de gestion", "Sciences de gestion"),
("BAB2 - Sc. de gestion (Ch)", "Sciences de gestion"),
("BAB2 - Sc. éco. et de gestion", "Sciences économiques et de gestion"),
("BAB2 - Sc. humaines et sociales", "SHS"),
("BAB2 - Sc. informatiques", "Sciences informatiques"),
("BAB2 - Sc. mathématiques", "Sciences mathématiques"),
("BAB2 - Sc. pharmaceutiques", "Sciences phamaceutiques"),
("BAB2 - Sc. physiques", "Sciences physiques"),
("BAB2 - Sc. psycho. et de l'éduc., or. générale", "Psychologie"),
("BAB2 - Sc. psycho. et de l'éduc., or. générale (Ch)", "Psychologie"),
("BAB2 - Sc. psycho. et de l'éduc., or. logop�die", "Psychologie"),
("BAB2 - Traduction et interprétation", "Traduction et interprétation"),
("BAB2 - Sc. humaines et sociales (Ch)", "SHS"),
("BAB3 - Architecture", "Architecture"),
("BAB3 - Droit", "Droit"),
("BAB3 - Ing. de gestion", "Ingénieur de gestion"),
("BAB3 - Ir. civil", "Polytech"),
("BAB3 - Ir. civil (Ch)", "Polytech"),
("BAB3 - Ir. civil architecte", "Polytech"),
("BAB3 - Médecine", "Médecine"),
("BAB3 - Sc. biologiques", "Sciences biologiques"),
("BAB3 - Sc. biologiques (Ch)", "Sciences biologiques"),
("BAB3 - Sc. biomédicales", "Sciences biomédicales"),
("BAB3 - Sc. chimiques", "Sciences chimiques"),
("BAB3 - Sc. de gestion", "Sciences de gestion"),
("BAB3 - Sc. de gestion (Ch)", "Sciences de gestion"),
("BAB3 - Sc. éco. et de gestion", "Sciences économiques et de gestion"),
("BAB3 - Sc. humaines et sociales", "SHS"),
("BAB3 - Sc. informatiques", "Sciences informatiques"),
("BAB3 - Sc. mathématiques", "Sciences mathématiques"),
("BAB3 - Sc. pharmaceutiques", "Sciences phamaceutiques"),
("BAB3 - Sc. physiques", "Sciences physiques"),
("BAB3 - Sc. Psycho. et de l'éduc., or. générale", "Psychologie"),
("BAB3 - Sc. psycho. et de l'éduc., or. générale (Ch)", "Psychologie"),
("BAB3 - Sc. psycho. et de l'éduc., or. logop�die", "Psychologie"),
("BAB3 - Traduction et interprétation", "Traduction et interprétation"),
("BAB3 - Sc. humaines et sociales (Ch)", "SHS"),
("Bloc compl. MA - Politique éco. et sociale", "Politique économique et sociale"),
("Bloc compl. MA - Sc. de gestion", "Sciences de gestion"),
("Bloc compl. MA - Sc. de gestion (Ch)", "Sciences de gestion"),
("Bloc compl. MA - Sc. informatiques", "Sciences informatiques"),
("Bloc compl. MA - Sc. informatiques (Ch)", "Sciences informatiques"),
("Bloc compl. MA - Transitions et innovations soc.", "SHS"),
("MA60 - Sc. biologiques", "Sciences biologiques"),
("MA60 - Sc. chimiques", "Sciences chimiques"),
("MA60 - Sc. de gestion", "Sciences de gestion"),
("MA60 - Sc. de gestion (Ch)", "Sciences de gestion"),
("MA60 - Sc. informatiques", "Sciences informatiques"),
("MA60 - Sc. informatiques (Ch)", "Sciences informatiques"),
("MA60 - Sc. mathématiques", "Sciences mathématiques"),
("MA60 - Sc. physiques", "Sciences physiques"),
("MAB1 - Alternance - Sc. informatiques, FS prof. (Ch)", "Sciences informatiques"),
("MAB1 - Architecture, FS art de bâtir", "Architecture"),
("MAB1 - Architecture, FS urbanisme", "Architecture"),
("MAB1 - Biochimie et bio. mol. et cellulaire", "Sciences biologiques"),
("MAB1 - Biochimie et bio. mol. et cellulaire (Ch)", "Sciences biologiques"),
("MAB1 - Biologie des organismes et écologie", "Sciences biologiques"),
("MAB1 - Ing. de gestion, FS", "Ingénieur de gestion"),
("MAB1 - Interprétation", "Traduction et interprétation"),
("MAB1 - Ir. civil architecte, FS", "Polytech"),
("MAB1 - Ir. civil chimie et SDM, FS", "Polytech"),
("MAB1 - Ir. civil électricien, FS", "Polytech"),
("MAB1 - Ir. civil énergie, FS Energy Production & Usage in Industr", "Polytech"),
("MAB1 - Ir. civil énergie, FS Energy Usage in Cities& Communities", "Polytech"),
("MAB1 - Ir. civil informatique et gestion (Ch)", "Polytech"),
("MAB1 - Ir. civil informatique et gestion, FS AIDA", "Polytech"),
("MAB1 - Ir. civil informatique et gestion, FS Cybersecurity", "Polytech"),
("MAB1 - Ir. civil mécanicien, FS", "Polytech"),
("MAB1 - Ir. civil mines et géologue, FS", "Polytech"),
("MAB1 - Médecine", "Médecine"),
("MAB1 - Politique éco. et soc., FS coll. terr.", "Politique économique et sociale"),
("MAB1 - Politique éco. et soc., FS pol. éco. soc.", "Politique économique et sociale"),
("MAB1 - Politique éco. et soc., FS socio-pol.", "Politique économique et sociale"),
("MAB1 - Sc. biomédicales, FA", "Sciences biomédicales"),
("MAB1 - Sc. biomédicales, FS neuroscience", "Sciences biomédicales"),
("MAB1 - Sc. chimiques", "Sciences chimiques"),
("MAB1 - Sc. de gestion, FD", "Sciences de gestion"),
("MAB1 - Sc. de gestion, FS", "Sciences de gestion"),
("MAB1 - Sc. de gestion, FS management (Ch)", "Sciences de gestion"),
("MAB1 - Sc. de l'éducation, FA", "Sciences de l'éducation"),
("MAB1 - Sc. de l'éducation, FS action sociale", "Sciences de l'éducation"),
("MAB1 - Sc. de l'éducation, FS action sociale (Ch)", "Sciences de l'éducation"),
("MAB1 - Sc. de l'éducation, FS enseignement", "Sciences de l'éducation"),
("MAB1 - Sc. de l'éducation, FS enseignement (Ch)", "Sciences de l'éducation"),
("MAB1 - Sc. de l'éducation, FS technologie", "Sciences de l'éducation"),
("MAB1 - Sc. de l'éducation, FS technologie (Ch)", "Sciences de l'éducation"),
("MAB1 - Sc. infirmières", "Sciences infirmières"),
("MAB1 - Sc. informatiques, FA", "Sciences informatiques"),
("MAB1 - Sc. informatiques, FS", "Sciences informatiques"),
("MAB1 - Sc. informatiques, FS AIDA", "Sciences informatiques"),
("MAB1 - Sc. mathématiques, FA", "Sciences mathématiques"),
("MAB1 - Sc. mathématiques, FD", "Sciences mathématiques"),
("MAB1 - Sc. mathématiques, FS finance", "Sciences mathématiques"),
("MAB1 - Sc. mathématiques, FS informatique", "Sciences mathématiques"),
("MAB1 - Sc. pharmaceutiques", "Sciences phamaceutiques"),
("MAB1 - Sc. physiques, FA", "Sciences physiques"),
("MAB1 - Sc. physiques, FD", "Sciences physiques"),
("MAB1 - Sc. psychologiques, FA", "Psychologie"),
("MAB1 - Sc. psychologiques, FS", "Psychologie"),
("MAB1 - Traduction, FA", "Traduction et interprétation"),
("MAB1 - Traduction, FD", "Traduction et interprétation"),
("MAB1 - Traduction, FS trad. interculturel", "Traduction et interprétation"),
("MAB1 - Traduction, FS trad. multidisciplinaire", "Traduction et interprétation"),
("MAB1 - Transitions et innovations soc.", "SHS"),
("MAB1 - Urba et Dév territorial (Ch)", "Architecture"),
("MAB1 en orthopédagogie clinique", "Psychologie"),
("MAB2 - Alternance - Sc. informatiques, FS prof. (Ch)", "Sciences informatiques"),
("MAB2 - Architecture, FS art de bâtir", "Architecture"),
("MAB2 - Architecture, FS urbanisme", "Architecture"),
("MAB2 - Biochimie et bio. mol. et cellulaire (Ch)", "Sciences biologiques"),
("MAB2 - Biochimie et bio. mol. et cellulaire, FA", "Sciences biologiques"),
("MAB2 - Biochimie et bio. mol. et cellulaire, FD", "Sciences biologiques"),
("MAB2 - Biochimie et bio. mol. et cellulaire, FS", "Sciences biologiques"),
("MAB2 - Biologie des organismes et écologie, FA", "Sciences biologiques"),
("MAB2 - Biologie des organismes et écologie, FD", "Sciences biologiques"),
("MAB2 - Biologie des organismes et écologie, FS", "Sciences biologiques"),
("MAB2 - Ing. de gestion, FS", "Ingénieur de gestion"),
("MAB2 - Interprétation", "Traduction et interprétation"),
("MAB2 - Ir. civil architecte, FS", "Polytech"),
("MAB2 - Ir. civil chimie et SDM, FS", "Polytech"),
("MAB2 - Ir. civil électricien, FS", "Polytech"),
("MAB2 - Ir. civil génie de l'énergie, FS Energy Production & Usage", "Polytech"),
("MAB2 - Ir. civil génie de l'énergie, FS Energy Usage in Cities", "Polytech"),
("MAB2 - Ir. civil informatique et gestion, FS AIDA", "Polytech"),
("MAB2 - Ir. civil informatique et gestion, FS Cybersecurity", "Polytech"),
("MAB2 - Ir. civil mécanicien, FS", "Polytech"),
("MAB2 - Ir. civil mines et géologue, FS", "Polytech"),
("MAB2 - Politique éco. et soc., FS coll. terr.", "Politique économique et sociale"),
("MAB2 - Politique éco. et soc., FS pol. éco. soc.", "Politique économique et sociale"),
("MAB2 - Politique éco. et soc., FS socio-pol.", "Politique économique et sociale"),
("MAB2 - Sc. biomédicales, FA", "Sciences biomédicales"),
("MAB2 - Sc. biomédicales, FS neuroscience", "Sciences biomédicales"),
("MAB2 - Sc. chimiques, FA", "Sciences chimiques"),
("MAB2 - Sc. chimiques, FD", "Sciences chimiques"),
("MAB2 - Sc. chimiques, FS entreprise", "Sciences chimiques"),
("MAB2 - Sc. de gestion, FD", "Sciences de gestion"),
("MAB2 - Sc. de gestion, FS", "Sciences de gestion"),
("MAB2 - Sc. de gestion, FS", "Sciences de gestion"),
("MAB2 - Sc. de l'éducation, FA", "Sciences de l'éducation"),
("MAB2 - Sc. de l'éducation, FS action sociale", "Sciences de l'éducation"),
("MAB2 - Sc. de l'éducation, FS action sociale (Ch)", "Sciences de l'éducation"),
("MAB2 - Sc. de l'éducation, FS enseignement", "Sciences de l'éducation"),
("MAB2 - Sc. de l'éducation, FS enseignement (Ch)", "Sciences de l'éducation"),
("MAB2 - Sc. de l'éducation, FS technologie", "Sciences de l'éducation"),
("MAB2 - Sc. de l'éducation, FS technologie (Ch)", "Sciences de l'éducation"),
("MAB2 - Sc. infirmières", "Sciences infirmières"),
("MAB2 - Sc. informatiques, FA", "Sciences informatiques"),
("MAB2 - Sc. informatiques, FS", "Sciences informatiques"),
("MAB2 - Sc. informatiques, FS AIDA", "Sciences informatiques"),
("MAB2 - Sc. mathématiques, FA", "Sciences mathématiques"),
("MAB2 - Sc. mathématiques, FD", "Sciences mathématiques"),
("MAB2 - Sc. pharmaceutiques", "Sciences phamaceutiques"),
("MAB2 - Sc. physiques, FA", "Sciences physiques"),
("MAB2 - Sc. physiques, FD", "Sciences physiques"),
("MAB2 - Sc. psychologiques, FA", "Psychologie"),
("MAB2 - Sc. psychologiques, FS", "Psychologie"),
("MAB2 - Traduction, FD", "Traduction et interprétation"),
("MAB2 - Traduction, FS trad. interculturel", "Traduction et interprétation"),
("MAB2 - Traduction, FS trad. multidisciplinaire", "Traduction et interprétation"),
("MAB2 - Transitions et innovations soc.", "SHS"),
("MAB2 en é clinique", "Psychologie"),
("MS - Etudes de genres", "Autres"),
("MS - Gestion des risques et bien-être au travail", "Autres"),
("MS - Gestion totale de la qualité", "Autres"),
("MS - Linguistique appliquée", "Autres"),
("MS - Nanotechnologies", "Autres"),
("MS - Péda. univ. et de l'ens. sup.", "Autres"),
("MS - Public health methodology", "Autres"),
("MS - Sc. Langage ", "Autres"),
("MS en formation d'enseignants", "Autres"),
("MS en management territorial et dév urbain", "Autres"),
("AESS - Art de bâtir et urbanisme", "Autres"),
("AESS - Langues, lettres et traductologie", "Autres"),
("AESS - Sc. biologiques", "Autres"),
("AESS - Sc. biomed. et pharma.", "Autres"),
("AESS - Sc. chimiques", "Autres"),
("AESS - Sc. de l'ingénieur et techno.", "Autres"),
("AESS - Sc. éco. et de gestion", "Autres"),
("AESS - Sc. Informatique", "Autres"),
("AESS - Sc. mathématiques", "Autres"),
("AESS - Sc. physiques", "Autres"),
("AESS - Sc. politiques et sociales", "Autres"),
("AESS - Sc. psycho. et de l'éduc.", "Autres"),
("CAPAES (non porteurs)", "Autres"),
("CAPAES (porteurs)", "Autres")]